#pragma config(Motor,  motor1,          MotorDriveL,   tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          MotorDriveR,   tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor10,         MotorArm,      tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor11,         MotorClaw,     tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*-----------------------------------------------------------------------------*/
/*                                                                             */
/*                        Copyright (c) James Pearman                          */
/*                                   2016                                      */
/*                            All Rights Reserved                              */
/*                                                                             */
/*-----------------------------------------------------------------------------*/
/*                                                                             */
/*    Module:     iqDefaultCodeBasic.c                                         */
/*    Author:     James Pearman                                                */
/*    Created:    31 Jan 2016                                                  */
/*                                                                             */
/*                V1.00 31 Jan 2016  Initial release tested with V4.52         */
/*                                                                             */
/*-----------------------------------------------------------------------------*/
/*                                                                             */
/*    The author is supplying this software for use with the VEX IQ            */
/*    control system. This file can be freely distributed and teams are        */
/*    authorized to freely use this program , however, it is requested that    */
/*    improvements or additions be shared with the Vex community via the vex   */
/*    forum.  Please acknowledge the work of the authors when appropriate.     */
/*    Thanks.                                                                  */
/*                                                                             */
/*    Licensed under the Apache License, Version 2.0 (the "License");          */
/*    you may not use this file except in compliance with the License.         */
/*    You may obtain a copy of the License at                                  */
/*                                                                             */
/*      http://www.apache.org/licenses/LICENSE-2.0                             */
/*                                                                             */
/*    Unless required by applicable law or agreed to in writing, software      */
/*    distributed under the License is distributed on an "AS IS" BASIS,        */
/*    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. */
/*    See the License for the specific language governing permissions and      */
/*    limitations under the License.                                           */
/*                                                                             */
/*    The author can be contacted on the vex forums as jpearman                */
/*    or electronic mail using jbpearman_at_mac_dot_com                        */
/*    Mentor for team 8888 RoboLancers, Pasadena CA.                           */
/*                                                                             */
/*-----------------------------------------------------------------------------*/
/*                                                                             */
/*    Description:                                                             */
/*                                                                             */
/*    Simple, basic control of VexIQ clawbot                                   */
/*                                                                             */
/*    PORT1  Left Drive Motor                                                  */
/*    PORT6  Right Drive Motor                                                 */
/*    PORT10 Arm Motor                                                         */
/*    PORT11 Claw Motor                                                        */
/*                                                                             */
/*-----------------------------------------------------------------------------*/

#if !defined(VexIQ)
#error "This code is for the VexIQ platform"
#else

//#define   ARCADE_DRIVE

/*-----------------------------------------------------------------------------*/
/*  Control robot wheels                                                       */
/*-----------------------------------------------------------------------------*/
void
iqRunRobotDrive( )
{
    long leftDrive;
    long rightDrive;

#if defined(ARCADE_DRIVE)
    short   forward, turn;

    // Get controller - use ChA for forward and ChB as turning
    forward = vexRT[ ChA ];
    turn    = vexRT[ ChB ];

    // Deadband set to 10
    if( abs( forward ) < 10 ) forward = 0;
    if( abs( turn )    < 10 ) turn    = 0;

    // Set drive
    leftDrive  = forward + turn;
    rightDrive = forward - turn;
#else
    // Tack drive
    leftDrive  = vexRT[ ChA ];
    rightDrive = vexRT[ ChD ];
    // Deadband set to 10
    if( abs( leftDrive )  < 10 ) leftDrive  = 0;
    if( abs( rightDrive ) < 10 ) rightDrive = 0;
#endif

    // Send to motors
    // left drive
    setMotorSpeed(MotorDriveL, leftDrive);

    // right drive
    setMotorSpeed(MotorDriveR, rightDrive);
}

/*-----------------------------------------------------------------------------*/
/*  Control the Auxiliary motors ports 10 & 11 for arm and claw                */
/*-----------------------------------------------------------------------------*/
void
iqRunRobotAux()
{
    int m10Drive;
    int m11Drive;

    // Control the auxilary motors
    m10Drive = (vexRT[ BtnLUp ] * 100) - (vexRT[ BtnLDown ] * 100);
    m11Drive = (vexRT[ BtnEUp ] * 100) - (vexRT[ BtnEDown ] * 100);

    // Arm motor
    setMotorSpeed( MotorArm, m10Drive );
    // Claw motor
    setMotorSpeed( MotorClaw, m11Drive );
}

/*-----------------------------------------------------------------------------*/
/*  Main entry                                                                 */
/*-----------------------------------------------------------------------------*/
task main()
{
    // driver control loop runs forever.
    while(1)
        {
        iqRunRobotDrive();
        iqRunRobotAux();
        wait1Msec(25);
        }
}

/*-----------------------------------------------------------------------------*/
#endif // #if defined(VexIQ)
